# Quagga OSPF
#
# VERSION 0.0.2
FROM nginx:1.13.0-alpine
LABEL maintainer.name="Nahuel Oliva - Cancinos Jose" \
      maintainer.email="nadaol@hotmail.com" \
      version="0.0.2" \
      description="nginx - apline based image"
RUN apk add --update net-tools
RUN apk add --update iproute2
RUN apk add --update tcpdump
