version: '2.1'

services:
  r1:
    build: .
    volumes:
      - ./volumes/quagga/r1/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r1/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r1/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image: alpine_quagga:1.0
    privileged: true
    ports:
      #admin
      - 10011:2601
      #ospf
      - 10012:2604
      #ospf ipv6
      - 10013:2606
    networks:
      oam:
        ipv4_address: 192.168.12.1
        ipv6_address: 2001:11::11
      nr3:
        ipv4_address: 192.168.13.1
        ipv6_address: 2001:13::11
          
  r2:
    build: .
    volumes:
      - ./volumes/quagga/r2/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r2/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r2/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image: alpine_quagga:1.0
    privileged: true
    ports:
      #admin
      - 10021:2601
      #ospf
      - 10022:2604
      #ospf ipv6
      - 10023:2606
    networks:
      oam:
        ipv4_address: 192.168.12.2
        ipv6_address: 2001:11::12
      nr2:
        ipv4_address: 192.168.2.1
        ipv6_address: 2001:12::11
      nr4:
        ipv4_address: 192.168.23.1
        ipv6_address: 2001:14::11  
  r3:
    build: .
    volumes:
      - ./volumes/quagga/r3/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r3/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r3/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image: alpine_quagga:1.0
    privileged: true
    ports:
      #admin
      - 10031:2601
      #ospf
      - 10032:2604
      #ospf ipv6
      - 10033:2606
    networks:
      nr3:
        ipv4_address: 192.168.13.2
        ipv6_address: 2001:13::12
      nr4:
        ipv4_address: 192.168.23.2
        ipv6_address: 2001:14::12
      nr5:
        ipv4_address: 192.168.34.1
        ipv6_address: 2001:15::11
      nr6:
        ipv4_address: 192.168.35.1
        ipv6_address: 2001:16::11  
        
  r4:
    build: .
    volumes:
      - ./volumes/quagga/r4/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r4/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r4/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image: alpine_quagga:1.0
    privileged: true
    ports:
      #admin
      - 10041:2601
      #ospf
      - 10042:2604
      #ospf ipv6
      - 10043:2606
    networks:
      nr5:
        ipv4_address: 192.168.34.2
        ipv6_address: 2001:15::12
      nr7:
        ipv4_address: 192.168.4.1
        ipv6_address: 2001:17::11
      nr8:
        ipv4_address: 192.168.45.1
        ipv6_address: 2001:18::11  

  r5:
    build: .
    volumes:
      - ./volumes/quagga/r5/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r5/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r5/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image: alpine_quagga:1.0
    privileged: true
    ports:
      #admin
      - 10051:2601
      #ospf
      - 10052:2604
      #ospf ipv6
      - 10053:2606
    networks:
      nr6:
        ipv4_address: 192.168.35.2
        ipv6_address: 2001:16::12
      nr8:
        ipv4_address: 192.168.45.2
        ipv6_address: 2001:18::12
      nr9:
        ipv4_address: 192.168.5.1
        ipv6_address: 2001:13::11  

networks:
  oam:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.12.0/24
        - subnet: 2001:11::/64
  nr2:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
        - subnet: 2001:12::/64
  nr3:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.13.0/24
        - subnet: 2001:13::/64
  nr4:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.23.0/24
        - subnet: 2001:14::/64
  nr5:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.34.0/24
        - subnet: 2001:15::/64
  nr6:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.35.0/24
        - subnet: 2001:16::/64
  nr7:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.4.0/24
        - subnet: 2001:17::/64
  nr8:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.45.0/24
        - subnet: 2001:18::/64
  nr9:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.0/24
        - subnet: 2001:19::/64

