version: '2.1'

services:
  r1:
    build: .
    volumes:
      - ./volumes/quagga/r1/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r1/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r1/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image: alpine_quagga:1.0
    privileged: true
    ports:
      #admin
      - 10011:2601
      #ospf
      - 10012:2604
      #ospf ipv6
      - 10013:2606
    networks:
      nr1r2:
        ipv4_address: 192.168.11.11
      nr1r3:
        ipv4_address: 192.168.13.11
          
  r2:
    build: .
    volumes:
      - ./volumes/quagga/r2/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r2/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r2/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image: alpine_quagga:1.0
    privileged: true
    ports:
      #admin
      - 10021:2601
      #ospf
      - 10022:2604
      #ospf ipv6
      - 10023:2606
    networks:
      nr1r2:
        ipv4_address: 192.168.11.12
      nr2r3:
        ipv4_address: 192.168.12.11
      nr2sw1:
        ipv4_address: 192.168.22.10
  r3:
    build: .
    volumes:
      - ./volumes/quagga/r3/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r3/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r3/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image: alpine_quagga:1.0
    privileged: true
    ports:
      #admin
      - 10031:2601
      #ospf
      - 10032:2604
      #ospf ipv6
      - 10033:2606
    networks:
      nr1r3:
        ipv4_address: 192.168.13.12
      nr2r3:
        ipv4_address: 192.168.12.12
      nr3r4:
        ipv4_address: 192.168.14.11
      nr3r5:
        ipv4_address: 192.168.15.12
        
  r4:
    build: .
    volumes:
      - ./volumes/quagga/r4/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r4/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r4/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image: alpine_quagga:1.0
    privileged: true
    ports:
      #admin
      - 10041:2601
      #ospf
      - 10042:2604
      #ospf ipv6
      - 10043:2606
    networks:
      nr3r4:
        ipv4_address: 192.168.14.12
      nr4r5:
        ipv4_address: 192.168.16.11
      nh4r4:
        ipv4_address: 192.168.24.11

  r5:
    build: .
    volumes:
      - ./volumes/quagga/r5/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r5/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r5/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image: alpine_quagga:1.0
    privileged: true
    ports:
      #admin
      - 10051:2601
      #ospf
      - 10052:2604
      #ospf ipv6
      - 10053:2606
    networks:
      nr3r5:
        ipv4_address: 192.168.15.11
      nr4r5:
        ipv4_address: 192.168.16.12
      nh5r5:
        ipv4_address: 192.168.25.11
  
  h1:
    image: alpine:latest
    privileged: true
    command: top
    networks:
      nr2sw1:
        ipv4_address: 192.168.22.11

  h2:
    image: alpine:latest
    privileged: true
    command: top
    networks:
      nr2sw1:
        ipv4_address: 192.168.22.12

  h3:
    image: alpine:latest
    privileged: true
    command: top
    networks:
      nr2sw1:
        ipv4_address: 192.168.22.13

  h4:
    image: alpine:latest
    privileged: true
    command: top
    networks:
      nh4r4:
        ipv4_address: 192.168.24.12

  h5:
    image: alpine:latest
    privileged: true
    command: top
    networks:
      nh5r5:
        ipv4_address: 192.168.25.12

networks:
  nr1r2:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 192.168.11.0/24
  nr1r3:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 192.168.13.0/24
  nr2r3:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 192.168.12.0/24
  nr2sw1:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 192.168.22.0/24

  nr3r4:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 192.168.14.0/24
  nr3r5:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 192.168.15.0/24
  nr4r5:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 192.168.16.0/24
  nh4r4:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 192.168.24.0/24

  nh5r5:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 192.168.25.0/24

